@Api_HostAddress = https://angular-book-app-eeb487910d5c.herokuapp.com

GET {{Api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{Api_HostAddress}}/api/Books
Accept: application/json

###

POST {{Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###

POST {{Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "username": "newuser",
  "password": "newpassword"
}

###

GET {{Api_HostAddress}}/api/protected
Accept: application/json
Authorization: Bearer {{your_jwt_token}}

###
